{
 "title": "Системные метрики",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Среднее время отклика эндпоинтов за последнюю минуту",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(request_duration_seconds_sum{job=\"fastapi_metrics\", endpoint!=\"/metrics\", endpoint!=\"/business_metrics\"}[1m]) / rate(request_duration_seconds_count{job=\"fastapi_metrics\"}[1m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Ошибки HTTP",
   "type": "gauge",
   "description": "4хх и 5хх ошибки работы сервиса",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_errors_4xx_total{job=\"fastapi_metrics\"}",
     "legendFormat": "{{http_code}}"
    }
   ]
  },
  {
   "title": "Количество запросов к эндпоинтам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "request_count_total{endpoint!=\"/metrics\", endpoint!=\"/business_metrics\", job=\"fastapi_metrics\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}